### PR TITLE
Database share token (#157)

### PR DESCRIPTION
**Pull request by j-berman**
## Overview

A user can now share databases with _any_ other user by generating a share token for that database.

```
userbase.shareDatabase({
    databaseName: 'example-database-name'
}).then(({ shareToken }) => {
    // Any other user can now open the database using this share token      
}).catch((e) => console.error(e))
```

The function also accepts a `readOnly` parameter to set access permissions for the token.

Credit to @fenske and @notrab for the request in #157!

### Generic state support (@fenske's use case)

_You want to create a web app that serves coding challenges to your users._

You can open a database, or multiple databases, add your coding challenges to the database(s), then generate a read-only share token for each database. Then hardcode the share token(s) into your web app, and all signed in users will have real-time access to the challenges.

### Authenticated access to global data (@notrab's use case, kind of)

_You want to create a blog where users need special authentication in order to comment on blog posts, but all users can read the comments._

For each blog post you create, you can open a database for the blog post's comments, then generate both a read-only token and write token for that database. The read-only token can safely be hardcoded into the web app, however, the write token must sit behind a server. Assuming you have access to a server-side environment such as a cloud function, hardcode the write token as an environment variable. When a user wants to comment, they make a request to your server, where you authenticate them via the Admin API's [Verify Auth Token endpoint](https://userbase.com/docs/api/verify-auth-token/), then retrieve the user via [Get User](https://userbase.com/docs/api/get-user/) and use the `protectedProfile` attribute to authenticate the special users who are able to comment. The users able to comment can be passed the write token as a response, and could then post a comment.

### Sharing data with trusted parties

_You want to create a file sharing site._

When a user wants to upload a file, they open a database, [upload the file ](https://userbase.com/docs/sdk/upload-file/), then generate a share token. The user can then give their friend a link with the share token embedded into it. The friend could then visit the site using the link, sign up, and download the file.

### Collaborating among trusted parties

_You want to create a Google Docs alternative._

When a user creates a document, they open a new database and generate a share token. To invite others to the doc, the user can create a special link with the share token embedded into it, and give the link to desired collaborators. Collaborators could then visit the site using the link, sign up, and begin editing the doc.

## Current Limitations

1. A user must be signed in order to access a database via a share token. We're considering allowing non-signed in users to access databases via the share token as well, or instead allowing admins to access data server-side via a separate SDK. See discussion of this in #157.

2. Each database can have two existing share tokens at a time - a read-only token, and a write token. Generating a new share token overwrites the existing share token that has the provided read/write permissions set.

### CODE REVIEW

**Comment by notrab** [comment]
@j-berman I'm actually implementing this now in a project. 

The use case is a video subscription site. Do you have some time to help me figure out the specifics a bit more? I'm comfortable authorizing an API request, etc. I'm just curious a bit more on your thoughts around opening each of the databases, and allowing anyone to comment, and then proxying the requests to write with the admin SDK etc.

Happy to jump on a call if it's easier 😄 

Thank you

**Comment by notrab** [comment]
That would be great! (More detailed explanation)

**Comment by j-berman** [comment]
Just going to focus on the comments part in this explanation for now. I'm going to assume you're using a serverless solution, like cloud functions in Netlify. Happy to provide further detail if needed.

Also, I'm sorry for the delay again! Been super focused on some work that's been taking up 110% of my time lately.

### User Story Overview

As the admin of a site, you upload videos to the site, and want to allow **paid** users to post comments on those videos. Anyone who visits the site should be able to **read** comments on videos.

#### Step 1: Create an admin account that will create comments databases

Using userbase-js-node, just sign up an account with username admin, and randomly generated password.

#### Step 2: Creating a comments database when uploading a video

While signed in to the admin account from above, create the comments database:

```
userbase.openDatabase({
  databaseName: videoName + '_comments',
  changeHandler: function (items) {
    // don't worry about this for now
  }
}).then(() => {
  console.log('done!')
}).catch((e) => console.error(e))
```

#### Step 3: Writing comments

You'll want to authorize the user as paid, then write the comment.

The auth logic will look something like this pseudocode:
```
cons authenticateUser = (authCredentials, videoName, comment) => {
    const user = await verifyAuthCredentials(authCredentials)
    if (user.paid) postComment(videoName, comment)
    else throw 'unpaid'
}
```

Now writing a comment will look something like this:
```
const postComment = async (videoName, comment) => {
  const databaseName = videoName + '_comments'
  
  await userbase.openDatabase({
      databaseName,
      changeHandler: function () {} // no-op
  })
  
  await userbase.insertItem({ databaseName, item: { comment } })
}
```


#### Step 4: Reading comments

This is pretty simple, just need to open the database:

```
const readComments = async (videoName) => {
  let comments
  const databaseName = videoName + '_comments'
  await userbase.openDatabase({
      databaseName,
      changeHandler: function (items) {
          comments = items
      }
  })
  
  return comments
}
```

### Final misc. thought

You might want to think about how you're naming videos too. Since there is no way to delete or modify database names today, this may pose a challenge. In another Userbase app I made, I used a database of databases to allow renaming of the thing I was working with. For example, you can have a database of video names, and the video names could correspond to a unique database ID. That unique ID can be what you use to open the database. This allows you to modify video names.

Does this all fit for what you were looking for?

**Comment by coderfin** [comment]
@j-berman 
In your [example](https://github.com/smallbets/userbase/pull/250#issuecomment-819289854) above shouldn't the admin `openDatabase` be `shareDatabase`?

```js
userbase.shareDatabase({
  databaseName: videoName + '_comments',
  changeHandler: function (items) {
    // don't worry about this for now
  }
}).then((shareToken) => {
  console.log('done!')
}).catch((e) => console.error(e))
```

And wouldn't reading and writing comments by the user need to pass a `shareToken` that they got from... somewhere?
```js
await userbase.openDatabase({
      databaseName,
      changeHandler: function () {}, // no-op
      shareToken // share token from somewhere
  })
```

What you have makes it seem like you don't need to share the database or pass around a share token.  Or am I missing something?

**Comment by j-berman** [comment]
When I wrote that comment, I believe I was thinking all that code would be server-side (e.g. via cloud functions in Netlify). It wouldn't need the sharing feature at all actually as written you're correct (pretty confusing of me, apologies).

The problem with passing a write-able shareToken back to the user is that anyone with access to the shareToken can write to the database (e.g. the user can give the shareToken to a random person and that random person can write to the db too).

To get the benefit of the sharing feature from this PR, you could do the following:

Steps 1-3 remain the same, all execute on the server-side. Keep in mind that for step 2, you can also authenticate a user using the [Verify Auth Token](https://userbase.com/docs/api/verify-auth-token/) Admin API endpoint.

Step 4 would be similar to what you mention, and require some additional setup from the admin. The admin would first need to create a **read-only** shareToken as follows:

```js
userbase.shareDatabase({
  databaseName: videoName + '_comments',
  readOnly: true
}).then((shareToken) => {
  // save this shareToken
}).catch((e) => console.error(e))
```

Then you can embed this `shareToken` into your app, and read comments from your app as follows:

```js
userbase.openDatabase({
  shareToken: <read-only shareToken>,
  changeHandler: function (items) {
    // update your application state with the database items
  }
}).then(() => {
  // the changeHandler will get called everytime the database is written to
}).catch((e) => console.error(e)) 
```

**Comment by coderfin** [comment]
@j-berman Thanks for the clarification!  That makes sense

**Pull request merged**
